### ISSUE TITLE
Project run

### ISSUE THREAD

**Issue by alaawahbah** [dignite-projects/dignite-abp#27]
Hi 
I really appreciate your effort, and wish for your company to move forward. 

Please can you provide demo links, because the project not run properly.

And In Document please make the platform you're support is clear.

Regards...

**Comment by duguankui** [comment]
Thank you very much for your feedback.

Dignite Abp 1.0 is built on Abp Framework 7.3.0, so please make sure your computer has .NET Framework 7.0 installed.

Regarding the online version of the demo system, there are no immediate plans for it within the next two months. However, I will be working on developing an online running demo system.

We provide sample code, including the Notification System, Files Explorer, and Pure Theme. You can run these samples locally to experience the functionality.

Thank you for your support and understanding.
